Update verify-sigs.yml

diff --git a/.github/workflows/verify-sigs.yml b/.github/workflows/verify-sigs.yml
--- a/.github/workflows/verify-sigs.yml
+++ b/.github/workflows/verify-sigs.yml
@@ -31,6 +31,8 @@ jobs:
         run: |
           python --version
           match=$(python verify_sigs.py)
-          echo "Verification succeed: ${match}"
-          if [ ! succeed ]; then exit 1; fi
+          if [ $match == "False" ]; then
+            echo "!! Error: Hashes do not match"
+            exit 1
+          fi
           
